trigger:
  branches:
    include: # Only run builds for the main branch, and tagged releases such as v0.1.0
      - refs/heads/main
      - refs/tags/v*

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: GoTool@0
    inputs:
      version: '1.20.7'
    displayName: 'Install Go'

  - script: go run mage.go ConfigureAgent
    displayName: "Configure Agent"

  - script: mage Test
    displayName: 'Test'

  - script: mage XBuildAll
    displayName: 'Cross Compile'

  - script: mage Publish
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)
    displayName: 'Publish'
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
